/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface FractionalNftVaultInterface extends Interface {
    getFunction(nameOrSignature: "BASE_ETH_PER_TOKEN" | "MARKETPLACE_FEE" | "MAX_SHARES" | "TOKENS_PER_SHARE" | "_calculateSharesPrice" | "allowance" | "approve" | "balanceOf" | "buyShares" | "claimNftTo" | "decimals" | "depositNftToVault" | "factory" | "isShareholder" | "name" | "nftContract" | "onERC721Received" | "owner" | "redeemShares" | "renounceOwnership" | "shareHoldersCount" | "shareholders" | "sweepDust" | "symbol" | "tokenURI" | "totalSupply" | "transfer" | "transferFrom" | "transferOwnership" | "updatedETHPrice"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "OwnershipTransferred" | "ShareHoldersCountUpdated" | "SharesBought" | "SharesRedeemed" | "Transfer"): EventFragment;

    encodeFunctionData(functionFragment: 'BASE_ETH_PER_TOKEN', values?: undefined): string;
encodeFunctionData(functionFragment: 'MARKETPLACE_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SHARES', values?: undefined): string;
encodeFunctionData(functionFragment: 'TOKENS_PER_SHARE', values?: undefined): string;
encodeFunctionData(functionFragment: '_calculateSharesPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'buyShares', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimNftTo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositNftToVault', values?: undefined): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'isShareholder', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'nftContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'redeemShares', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'shareHoldersCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'shareholders', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'sweepDust', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatedETHPrice', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BASE_ETH_PER_TOKEN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MARKETPLACE_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SHARES', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TOKENS_PER_SHARE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: '_calculateSharesPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimNftTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositNftToVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isShareholder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nftContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeemShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shareHoldersCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shareholders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sweepDust', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatedETHPrice', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ShareHoldersCountUpdatedEvent {
      export type InputTuple = [For: AddressLike, Vaule: BigNumberish];
      export type OutputTuple = [For: string, Vaule: bigint];
      export interface OutputObject {For: string, Vaule: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SharesBoughtEvent {
      export type InputTuple = [vault: AddressLike, buyer: AddressLike, shares: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [vault: string, buyer: string, shares: bigint, timestamp: bigint];
      export interface OutputObject {vault: string, buyer: string, shares: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SharesRedeemedEvent {
      export type InputTuple = [vault: AddressLike, seller: AddressLike, shares: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [vault: string, seller: string, shares: bigint, timestamp: bigint];
      export interface OutputObject {vault: string, seller: string, shares: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FractionalNftVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): FractionalNftVault;
    waitForDeployment(): Promise<this>;

    interface: FractionalNftVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASE_ETH_PER_TOKEN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MARKETPLACE_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_SHARES: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TOKENS_PER_SHARE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    _calculateSharesPrice: TypedContractMethod<
      [_numberSharesToBuy: BigNumberish, ],
      [[bigint, bigint] & {requiredETH: bigint, numberOfRequiredTokens: bigint }],
      'view'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    buyShares: TypedContractMethod<
      [_numberSharesToBuy: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    claimNftTo: TypedContractMethod<
      [_to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    depositNftToVault: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isShareholder: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nftContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    onERC721Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    redeemShares: TypedContractMethod<
      [_sharesToRedeem: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    shareHoldersCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    shareholders: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    sweepDust: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatedETHPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASE_ETH_PER_TOKEN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MARKETPLACE_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SHARES'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TOKENS_PER_SHARE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: '_calculateSharesPrice'): TypedContractMethod<
      [_numberSharesToBuy: BigNumberish, ],
      [[bigint, bigint] & {requiredETH: bigint, numberOfRequiredTokens: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyShares'): TypedContractMethod<
      [_numberSharesToBuy: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'claimNftTo'): TypedContractMethod<
      [_to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'depositNftToVault'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isShareholder'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nftContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'redeemShares'): TypedContractMethod<
      [_sharesToRedeem: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shareHoldersCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'shareholders'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'sweepDust'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatedETHPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ShareHoldersCountUpdated'): TypedContractEvent<ShareHoldersCountUpdatedEvent.InputTuple, ShareHoldersCountUpdatedEvent.OutputTuple, ShareHoldersCountUpdatedEvent.OutputObject>;
getEvent(key: 'SharesBought'): TypedContractEvent<SharesBoughtEvent.InputTuple, SharesBoughtEvent.OutputTuple, SharesBoughtEvent.OutputObject>;
getEvent(key: 'SharesRedeemed'): TypedContractEvent<SharesRedeemedEvent.InputTuple, SharesRedeemedEvent.OutputTuple, SharesRedeemedEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ShareHoldersCountUpdated(address,uint256)': TypedContractEvent<ShareHoldersCountUpdatedEvent.InputTuple, ShareHoldersCountUpdatedEvent.OutputTuple, ShareHoldersCountUpdatedEvent.OutputObject>;
      ShareHoldersCountUpdated: TypedContractEvent<ShareHoldersCountUpdatedEvent.InputTuple, ShareHoldersCountUpdatedEvent.OutputTuple, ShareHoldersCountUpdatedEvent.OutputObject>;
    

      'SharesBought(address,address,uint256,uint256)': TypedContractEvent<SharesBoughtEvent.InputTuple, SharesBoughtEvent.OutputTuple, SharesBoughtEvent.OutputObject>;
      SharesBought: TypedContractEvent<SharesBoughtEvent.InputTuple, SharesBoughtEvent.OutputTuple, SharesBoughtEvent.OutputObject>;
    

      'SharesRedeemed(address,address,uint256,uint256)': TypedContractEvent<SharesRedeemedEvent.InputTuple, SharesRedeemedEvent.OutputTuple, SharesRedeemedEvent.OutputObject>;
      SharesRedeemed: TypedContractEvent<SharesRedeemedEvent.InputTuple, SharesRedeemedEvent.OutputTuple, SharesRedeemedEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    
    };
  }