/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'FractionalNFTsVaultsMarketplaceFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FractionalNFTsVaultsMarketplaceFactory__factory>
getContractFactory(name: 'FractionalNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FractionalNFT__factory>
getContractFactory(name: 'FractionalNftVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FractionalNftVault__factory>
getContractFactory(name: 'VaultToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VaultToken__factory>

  getContractAt(name: 'FractionalNFTsVaultsMarketplaceFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FractionalNFTsVaultsMarketplaceFactory>
getContractAt(name: 'FractionalNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FractionalNFT>
getContractAt(name: 'FractionalNftVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FractionalNftVault>
getContractAt(name: 'VaultToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VaultToken>

  deployContract(name: 'FractionalNFTsVaultsMarketplaceFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FractionalNFTsVaultsMarketplaceFactory>
deployContract(name: 'FractionalNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FractionalNFT>
deployContract(name: 'FractionalNftVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FractionalNftVault>
deployContract(name: 'VaultToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VaultToken>

  deployContract(name: 'FractionalNFTsVaultsMarketplaceFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FractionalNFTsVaultsMarketplaceFactory>
deployContract(name: 'FractionalNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FractionalNFT>
deployContract(name: 'FractionalNftVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FractionalNftVault>
deployContract(name: 'VaultToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VaultToken>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  