/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FractionalNFTsVaultsMarketplaceFactory__factory } from './FractionalNFTsVaultsMarketplaceFactory__factory.js';